version: '3.7'

services:
  riki:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - /path/to/host/markdown/pages/dir:/var/opt/riki/data
      - /path/to/local/riki/installation:/opt/riki
      - /path/to/host/search/index/dir:/var/opt/riki/srch-index
    networks:
      - rikinet

  nginx:
    image: nginx:latest
    environment:
      - TZ=Europe/Prague
    ports:
      - "8095:80"
    volumes:
      - ./nginx.docker.conf:/etc/nginx/conf.d/default.conf
      - ./static:/opt/riki/static
    networks:
      - rikinet
    depends_on:
      - riki

networks:
  rikinet: {}
